name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to deploy'
        required: true
        type: string
      cluster_name:
        description: 'ECS Cluster name'
        required: true
        type: string
env:
  AWS_REGION: ap-southeast-1
  ECR_REGISTRY: 253921445383.dkr.ecr.ap-southeast-1.amazonaws.com
  ECR_REPOSITORY: nodejs-random-color
  TASK_FAMILY: nodejs-task-definition
  SERVICE_NAME: nodejs-service

jobs:
  build:
    uses: ./.github/workflows/testbuild.yml
    with:
      version: ${{ inputs.version }}
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        mask-aws-account-id: false
        
    - name: Render new task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ./task-def.json
        container-name: nodejs-service
        image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ inputs.version }}

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.SERVICE_NAME }}
        cluster: ${{ inputs.cluster_name }}
        wait-for-service-stability: true
