name: Scale Down Old Service

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: "Tên ECS cluster"
        required: true
  workflow_call:
    inputs:
      cluster_name:
        description: 'ECS Cluster name to clear resources from'
        required: true
        type: string

jobs:
  scale-down:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Scale ECS Service to 0
        run: |
          aws ecs update-service \
            --cluster ${{ inputs.cluster_name }} \
            --service ${{ vars.service_name }} \
            --desired-count 0
