name: Scale Down Old Service

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: "Tên ECS cluster"
        required: true
      service_name:
        description: "Tên ECS service"
        required: true

jobs:
  scale-down:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-1
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Scale ECS Service to 0
        run: |
          aws ecs update-service \
            --cluster ${{ inputs.cluster_name }} \
            --service ${{ inputs.service_name }} \
            --desired-count 0
